### ISSUE TITLE
Error with large files

### ISSUE THREAD

**Issue by KillTheMule** [daa84/neovim-lib#10]
Hey, thanks for this lib, I'm just trying it out :)

I encountered a problem. When using the neovim plugin I started to write with files above a certain size (seems like 9.2MB is ok, 13.2MB and above is not) I encounter the following error:

> 09:29:20 [DEBUG] neovim_lib::rpc::client: [neovim-lib/src/rpc/client.rs:149] Error reading I/O error while reading marker byte: failed to fill whole buffer

Now, I'm very shaky on all the details, and the circumstances I'm working under are quiet complicated. That being said, maybe you can already tell what's going on? Maybe you can give me some hints how to dig into this issue? Or is that an issue of the msgpack library?

(E) Actually, let me clarify that the size of the files having something to do with it is a theory of mine. I tested with 8 files of varying size, and the size is the most obvious difference here, but of course there are other differences I can't fully account for.

**Comment by daa84** [comment]
Hello!
Looks like some buffer inside msgpack library or this library is to small for reading such big amount of data. 
I don't know use case, but maybe it is possible to write file by chunks or read/write file directly, without neovim msgpack api?
Anyway size of this buffer exists somewhere i think 😄

**Comment by daa84** [comment]
Hm, but it also can be neovim limitation.

**Comment by KillTheMule** [comment]
So the use case is using https://github.com/neovim/neovim/pull/5269 to track the buffer. This sends notifications with changes to the buffer, and in particular the first notification sends the whole buffer. That might be too large... not sure, the PR promises to split up things, but I've yet to see this.

**Comment by KillTheMule** [comment]
Hmm, ok, I've done a bit of investigation and setup, and I'm totally unclear on where the problem lies. Mind checking that out? I've put a repository at https://github.com/KillTheMule/nvimpam/, and the problem actually is a panic at https://github.com/KillTheMule/nvimpam/blob/master/src/main.rs#L141. I've added this function to the api manually at https://github.com/KillTheMule/nvimpam/blob/master/neovim-lib/src/neovim_api.rs#L198, and as I said it works for somewhat smaller files. For a larger file, I have a backtrace at https://github.com/KillTheMule/nvimpam/blob/master/nvimpam.stderr.

So the problem really is the function returning with an error. I can print it out, but it just says `GenericError("Wait timeout")`, and I'm a bit lost how to find the reason for that. Is that a problem with neovim-lib, or msgpack-rust? I'd be grateful for any help :)

**Comment by daa84** [comment]
It can be that call for large file take more time, default timeout is 5s, you can increase it by call https://github.com/KillTheMule/nvimpam/blob/2ba38fa259433dc751418eadd3775aaf1b2ca059/neovim-lib/src/session.rs#L104
or set to infinity (that is not recommended because on some errors neovim just stops response and your program will not terminate ever) 
https://github.com/KillTheMule/nvimpam/blob/2ba38fa259433dc751418eadd3775aaf1b2ca059/neovim-lib/src/session.rs#L108

**Comment by KillTheMule** [comment]
Thanks! So what do I do for a call I _really_ need to succeed? Loop?

**Comment by daa84** [comment]
Maybe implement also async call, so method will return special object with channel reciever, in this case you can wait for this particular call more time and leave all over calls with smaller wait timeout. Or maybe just set timeout to something big like 1minute. Anyway some timeout is needed so program can detect that something go wrong.

**Comment by KillTheMule** [comment]
So, when that call times out, can I be sure neovim did not get it? I need to make sure not to send it twice, I think.

**Comment by daa84** [comment]
No, timeout mean, neovim does not respond to this call. But the reason can be different. It can be that some error happens, it can be long processing time or maybe it doesn't return any value for this particular call. Maybe this is some special case or bug.

**Comment by KillTheMule** [comment]
Hrr, ok, I'll need to investigate, thanks for your help!

**Comment by KillTheMule** [comment]
It doesn't seem to be the timeout. I've started a bit of timestamping, and the "failed to fill whole buffer" error comes way earlier.

**Comment by KillTheMule** [comment]
Could I ask for your help again? I've kinda got to the root cause, I think, but I can't really figure what it means and what I could do about it...

So the error is from https://github.com/KillTheMule/nvimpam/blob/master/neovim-lib/src/rpc/client.rs#L149 and reads `[DEBUG] neovim_lib::rpc::client: [neovim-lib/src/rpc/client.rs:149] Error reading I/O error while reading marker byte: failed to fill whole buffer`.

This goes down as follows (you surely know): `model_decode` calls `rmpv::decode::read_value` on the reader (this should be stdin, right?), which calls `rmp::decode::read_marker` which finally calls `read_u8` from the `byteorder` crate, which is more or less an alias for `read_exact` for the stdlib `Reader`. And it's _this_ function that throws the `failed to fill whole buffer` error.

Now, what does it mean? I'd think `read_exact` could not get a byte (because the buffer is that small) from stdin. I'd expect stdin to be "empty" most of the time, but why is it a problem here? I have a hard time parsing the neovim-lib setup with the threads and how it all fits together still, so maybe you can give me some hint on what's happening (part of the reason I really want to find out is that there might be a bug in the neovim PR I'm testing, so that's surely a possibility).

**Comment by daa84** [comment]
Check code, and looks like this error happens when read returns 0 bytes, that mean eof. So maybe neovim for some reason send eof to stream?
https://doc.rust-lang.org/src/std/io/mod.rs.html#683
https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read

**Comment by KillTheMule** [comment]
I've sat with the neovim guys to analyze the rpc connection, and there's some oddity. My code is [here](https://github.com/KillTheMule/nvimpam/blob/master/src/main.rs#L141), there are 2 api calls. The second method is defined [here](https://github.com/KillTheMule/nvimpam/blob/master/neovim-lib/src/neovim_api.rs#L198), I verified that your autogenerate script generates exactly the same code (I also replaced the `call_args` invocation by manually assembling the vec, nothing changed).

I've recorded the mspack communication and decoded it (you can find it in the repo), and those 2 api calls generate the following calls

> [0,2,"nvim_get_current_buf",["quit"]]
> [0,3,"nvim_buf_live_updates",["quit"]]

This does not seem right. According to one of the devs, it should look like

> [0,6,"nvim_get_current_buf",[]]
> [0,7,"nvim_buf_live_updates",[codeobj, true]]

where `codeobj` is the return from the first call (so, sure, the curbuf object the method it's called on, I'd expect a `0` in this specific case).

Any idea how that could happen?

**Comment by daa84** [comment]
Looks really strange. I don't find any constant called "quit" in my library on in rmpv. But if it is true ["quit"] parameter looks like some error

**Comment by daa84** [comment]
Hmmm, "quit" in your code, maybe some issue with take previous arguments for next command

**Comment by KillTheMule** [comment]
Yeah "quit" looks like a leftover from the previous call. I'll try to dig into rmp/rmpv to see if there's some funky caching going on or so.

**Comment by boxofrox** [comment]
@KillTheMule double check your decodes.  I took a look at `/output/nvimpam_mid.stdout` and `/output/nvimpam_mid.stdout.decoded`.  The former only has one entry of "quit", while the latter has three.

I decoded the file by hand and put my worksheet in a gist \[[1](https://gist.github.com/boxofrox/ae6e264474652db00faefbec269da281)].

My decode of your last two API calls matches the form described by the neovim devs:

```
[ 0 6 nvim_get_current_buf [ ] ]
[ 0 7 nvim_buf_live_updates [ `extension type 0 data 1` true ] ]
```
I didn't decode `/output/nvimpam.stdout`, but looking at the file, it only has one "quit" entry also.

\[1]: https://gist.github.com/boxofrox/ae6e264474652db00faefbec269da281

**Comment by KillTheMule** [comment]
Uhhh thanks a lot! I did not decode by hand, but use a [cli prog](https://github.com/jakm/msgpack-cli). That of course adds another layer, might just be wrong.

I'll check again, and then I guess it's back to square one. Thanks again!

**Comment by boxofrox** [comment]
Looks like you can use msgpack-python to decode \[[1](https://github.com/jakm/msgpack-cli/issues/2)], too, instead of msgpack-cli.

```python
▶ python
Python 3.6.3 (default, Oct 24 2017, 14:48:20)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import msgpack
>>> file = open('output/nvimpam.stdout', 'rb')
>>> unpacker = msgpack.Unpacker(file)
>>> for pack in unpacker:
...     print(pack)
...
[0, 0, b'nvim_command', [b'echom "rust client connected to neovim"']]
[0, 1, b'nvim_subscribe', [b'LiveUpdateStart']]
[0, 2, b'nvim_subscribe', [b'LiveUpdate']]
[0, 3, b'nvim_subscribe', [b'LiveUpdateTick']]
[0, 4, b'nvim_subscribe', [b'LiveUpdateEnd']]
[0, 5, b'nvim_subscribe', [b'quit']]
[0, 6, b'nvim_get_current_buf', []]
[0, 7, b'nvim_buf_live_updates', [ExtType(code=0, data=b'\x01'), True]]
[0, 8, b'nvim_command', [b'normal! zE']]
[0, 9, b'nvim_command', [b'76,10522fo']]
[0, 10, b'nvim_command', [b'23775,23814fo']]
[0, 11, b'nvim_command', [b'silent! qa']]
>
```

\[1]: https://github.com/jakm/msgpack-cli/issues/2

**Comment by KillTheMule** [comment]
Just a bit of an update: After more investigation, it looks like an error on the side of neovim itself or the PR I'm using.

**Comment by KillTheMule** [comment]
It was neovim after all! The channel capacity was capped at 10MB, and neovim would still send larger messages, but close the channels afterwards. Quick fix in https://github.com/neovim/neovim/pull/7917/commits/151ec8ecd6c2fc170277912102c0df1857341e03, if anyone's interested!
