### ISSUE TITLE
Consider adding buffered reading

### ISSUE THREAD

**Issue by KillTheMule** [daa84/neovim-lib#15]
Heyho!

Would you consider buffered reading, or the option to have buffered reading to the lib? It can speed up the communication with neovim (probably a bottleneck for many applications... at least it is this way for my plugin for sure) greatly! Simply wrapping the reader in the [communication thread](https://github.com/daa84/neovim-lib/blob/master/src/rpc/client.rs#L195) in a `BufReader` reduced the time of the relevant benchmark of my plugin by 70%!

So would you consider that? If it proves troublesome, maybe a compile time option?

**Comment by daa84** [comment]
Hm, yes, this is really need to do thing :+1: . Maybe also together with BufWriter.

**Comment by KillTheMule** [comment]
Why don't I get notifications on commits on repositories I'm watching -.- Anyways, thanks for adding that.
